defaults: &defaults
  adapter: sqlite3

production:
  <<: *defaults
  database: dukejour

development:
  <<: *defaults
  database: db/dukejour_dev.sqlite3

test:
  <<: *defaults
  database: dukejour_test
